use Epic SDK 1.15.1

diff --git a/sauerbraten.app/Contents/MacOS/sauerbraten b/sauerbraten.app/Contents/MacOS/sauerbraten
--- a/sauerbraten.app/Contents/MacOS/sauerbraten
+++ b/sauerbraten.app/Contents/MacOS/sauerbraten
@@ -5,18 +5,22 @@ SAUER_OPTIONS=""
 
 # SAUER_HOME is where Sauerbraten should store user files.
 SAUER_HOME="${HOME}/Library/Application Support/Sauerbraten"
-SAUER_APPDIR=$(dirname "$0")
 
-cd "${SAUER_APPDIR}"
+cd "$(dirname "$0")"
 
-if [ -e "../Resources/data/defaults.cfg" ]; then
-    cd "../Resources" # we are an app package
-    SAUER_BIN="../MacOS"
-elif [ -e "../../../data/defaults.cfg" ]; then
-    cd "../../.." # we are being run in place
-    SAUER_BIN="./sauerbraten.app/Contents/MacOS"
+if [ -e "../Resources/data/stdlib.cfg" ]; then
+    # we are an app package
+    CONTENT_DIR="$(dirname $PWD)/Resources"
+elif [ -e "../../../data/stdlib.cfg" ]; then
+    # we are being run in place
+    CONTENT_DIR=$PWD
+    # todo: better way to walk up three levels and get an absolute path
+    CONTENT_DIR=$(dirname $CONTENT_DIR)
+    CONTENT_DIR=$(dirname $CONTENT_DIR)
+    CONTENT_DIR=$(dirname $CONTENT_DIR)
 else
-    SAUER_BIN="."
+    echo "cannot find content directory"
+    exit 1
 fi
 
-exec ${SAUER_BIN}/start_protected_game -e ${SAUER_OPTIONS} -q"${SAUER_HOME}" -glog.txt $@
+./start_protected_game.app/Contents/MacOS/start_protected_game -e -k"${CONTENT_DIR}" -q"${SAUER_HOME}" -glog.txt ${SAUER_OPTIONS} $@
